# Config file for go-test-coverage github action.

profile: cover.out
local-prefix: github.com/FIAP-SOAT-G20/tc4-order-service
threshold:
  total: 80
exclude:
  paths:
    - docs/*
    - internal/core/domain/value_object/*
    - jwt_service.go
    - ^.*_mock\.go$
    - ^.*_request\.go$
    - ^.*_response\.go$
    - ^.*_gateway\.go$
    - ^.*_datasource\.go$
    - ^.*_presenter\.go$
    - ^.*middleware.*
    - ^.*config.*
    - ^.*route.*
    - ^.*util.*
    - ^.*database.*
    - ^.*server.*
    - ^.*logger.*
    - ^.*httpclient.*
    - ^.*_entity\.go$
    - ^.*errors\.go$
    - ^.*_dto\.go$

