services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/fiap-soat-g20/fiap-tech-challenge-3-api:latest
    container_name: app.10soat-g22.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/ff_db_order?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ff_order_network
    restart: unless-stopped

  db:
    image: postgres:17-alpine3.21
    container_name: db-order.10soat-g22.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ff_db_order
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ff_order_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dbadmin:
    image: dpage/pgadmin4
    container_name: dbadmin.10soat-g22.dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ff_order_network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  ff_order_network:
    driver: bridge
