FROM mockoon/cli:9.2.0

LABEL org.opencontainers.image.source="https://github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api" \
      org.opencontainers.image.authors="FIAP 10SOAT G18" \
      org.opencontainers.image.title="Mercado Pago Mock Server" \
      org.opencontainers.image.description="Image of a mock backend API for Mercado Pago."

COPY ./mockserver/definition.json data/

CMD ["--data", "/data/definition.json", "--port", "3001"]
