version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "dev-1.24-bookworm"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
      - go-cache:/go
    environment:
      - DB_DSN=postgres://postgres:postgres@postgres:5432/fastfood_10soat_g22_tc3?sslmode=disable
    command: sleep infinity
    network_mode: service:postgres

  postgres:
    image: postgres:17-alpine3.21
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fastfood_10soat_g22_tc3

volumes:
  postgres-data:
  go-cache:
