DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_products;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS order_histories;
DROP TABLE IF EXISTS staffs;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;

DROP TYPE IF EXISTS order_status;
