// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/category_datasource_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/category_datasource_port.go -destination=internal/core/port/mocks/category_datasource_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryDataSource is a mock of CategoryDataSource interface.
type MockCategoryDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryDataSourceMockRecorder
	isgomock struct{}
}

// MockCategoryDataSourceMockRecorder is the mock recorder for MockCategoryDataSource.
type MockCategoryDataSourceMockRecorder struct {
	mock *MockCategoryDataSource
}

// NewMockCategoryDataSource creates a new mock instance.
func NewMockCategoryDataSource(ctrl *gomock.Controller) *MockCategoryDataSource {
	mock := &MockCategoryDataSource{ctrl: ctrl}
	mock.recorder = &MockCategoryDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryDataSource) EXPECT() *MockCategoryDataSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryDataSource) Create(ctx context.Context, category *entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCategoryDataSourceMockRecorder) Create(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryDataSource)(nil).Create), ctx, category)
}

// Delete mocks base method.
func (m *MockCategoryDataSource) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryDataSourceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryDataSource)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockCategoryDataSource) FindAll(ctx context.Context, filters map[string]any, page, limit int) ([]*entity.Category, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters, page, limit)
	ret0, _ := ret[0].([]*entity.Category)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCategoryDataSourceMockRecorder) FindAll(ctx, filters, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCategoryDataSource)(nil).FindAll), ctx, filters, page, limit)
}

// FindByID mocks base method.
func (m *MockCategoryDataSource) FindByID(ctx context.Context, id uint64) (*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCategoryDataSourceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCategoryDataSource)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockCategoryDataSource) Update(ctx context.Context, category *entity.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCategoryDataSourceMockRecorder) Update(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryDataSource)(nil).Update), ctx, category)
}
