// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/customer_controller_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/customer_controller_port.go -destination=internal/core/port/mocks/customer_controller_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	port "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/port"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerController is a mock of CustomerController interface.
type MockCustomerController struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerControllerMockRecorder
	isgomock struct{}
}

// MockCustomerControllerMockRecorder is the mock recorder for MockCustomerController.
type MockCustomerControllerMockRecorder struct {
	mock *MockCustomerController
}

// NewMockCustomerController creates a new mock instance.
func NewMockCustomerController(ctrl *gomock.Controller) *MockCustomerController {
	mock := &MockCustomerController{ctrl: ctrl}
	mock.recorder = &MockCustomerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerController) EXPECT() *MockCustomerControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerController) Create(ctx context.Context, presenter port.Presenter, input dto.CreateCustomerInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerControllerMockRecorder) Create(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerController)(nil).Create), ctx, presenter, input)
}

// Delete mocks base method.
func (m *MockCustomerController) Delete(ctx context.Context, presenter port.Presenter, input dto.DeleteCustomerInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerControllerMockRecorder) Delete(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerController)(nil).Delete), ctx, presenter, input)
}

// Get mocks base method.
func (m *MockCustomerController) Get(ctx context.Context, presenter port.Presenter, input dto.GetCustomerInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCustomerControllerMockRecorder) Get(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCustomerController)(nil).Get), ctx, presenter, input)
}

// List mocks base method.
func (m *MockCustomerController) List(ctx context.Context, presenter port.Presenter, input dto.ListCustomersInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomerControllerMockRecorder) List(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomerController)(nil).List), ctx, presenter, input)
}

// Update mocks base method.
func (m *MockCustomerController) Update(ctx context.Context, presenter port.Presenter, input dto.UpdateCustomerInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerControllerMockRecorder) Update(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerController)(nil).Update), ctx, presenter, input)
}
