// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_history_datasource_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_history_datasource_port.go -destination=internal/core/port/mocks/order_history_datasource_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderHistoryDataSource is a mock of OrderHistoryDataSource interface.
type MockOrderHistoryDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHistoryDataSourceMockRecorder
	isgomock struct{}
}

// MockOrderHistoryDataSourceMockRecorder is the mock recorder for MockOrderHistoryDataSource.
type MockOrderHistoryDataSourceMockRecorder struct {
	mock *MockOrderHistoryDataSource
}

// NewMockOrderHistoryDataSource creates a new mock instance.
func NewMockOrderHistoryDataSource(ctrl *gomock.Controller) *MockOrderHistoryDataSource {
	mock := &MockOrderHistoryDataSource{ctrl: ctrl}
	mock.recorder = &MockOrderHistoryDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHistoryDataSource) EXPECT() *MockOrderHistoryDataSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderHistoryDataSource) Create(ctx context.Context, entity *entity.OrderHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderHistoryDataSourceMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderHistoryDataSource)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockOrderHistoryDataSource) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderHistoryDataSourceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderHistoryDataSource)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockOrderHistoryDataSource) FindAll(ctx context.Context, filters map[string]any, page, limit int) ([]*entity.OrderHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters, page, limit)
	ret0, _ := ret[0].([]*entity.OrderHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrderHistoryDataSourceMockRecorder) FindAll(ctx, filters, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrderHistoryDataSource)(nil).FindAll), ctx, filters, page, limit)
}

// FindByID mocks base method.
func (m *MockOrderHistoryDataSource) FindByID(ctx context.Context, id uint64) (*entity.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderHistoryDataSourceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderHistoryDataSource)(nil).FindByID), ctx, id)
}

// Transaction mocks base method.
func (m *MockOrderHistoryDataSource) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockOrderHistoryDataSourceMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockOrderHistoryDataSource)(nil).Transaction), ctx, fn)
}
