// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_history_usecase_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_history_usecase_port.go -destination=internal/core/port/mocks/order_history_usecase_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderHistoryUseCase is a mock of OrderHistoryUseCase interface.
type MockOrderHistoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHistoryUseCaseMockRecorder
	isgomock struct{}
}

// MockOrderHistoryUseCaseMockRecorder is the mock recorder for MockOrderHistoryUseCase.
type MockOrderHistoryUseCaseMockRecorder struct {
	mock *MockOrderHistoryUseCase
}

// NewMockOrderHistoryUseCase creates a new mock instance.
func NewMockOrderHistoryUseCase(ctrl *gomock.Controller) *MockOrderHistoryUseCase {
	mock := &MockOrderHistoryUseCase{ctrl: ctrl}
	mock.recorder = &MockOrderHistoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHistoryUseCase) EXPECT() *MockOrderHistoryUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderHistoryUseCase) Create(ctx context.Context, input dto.CreateOrderHistoryInput) (*entity.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*entity.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderHistoryUseCaseMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderHistoryUseCase)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockOrderHistoryUseCase) Delete(ctx context.Context, input dto.DeleteOrderHistoryInput) (*entity.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*entity.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderHistoryUseCaseMockRecorder) Delete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderHistoryUseCase)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockOrderHistoryUseCase) Get(ctx context.Context, input dto.GetOrderHistoryInput) (*entity.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*entity.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderHistoryUseCaseMockRecorder) Get(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderHistoryUseCase)(nil).Get), ctx, input)
}

// List mocks base method.
func (m *MockOrderHistoryUseCase) List(ctx context.Context, input dto.ListOrderHistoriesInput) ([]*entity.OrderHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]*entity.OrderHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOrderHistoryUseCaseMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderHistoryUseCase)(nil).List), ctx, input)
}
