// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_product_controller_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_product_controller_port.go -destination=internal/core/port/mocks/order_product_controller_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	port "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/port"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderProductController is a mock of OrderProductController interface.
type MockOrderProductController struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProductControllerMockRecorder
	isgomock struct{}
}

// MockOrderProductControllerMockRecorder is the mock recorder for MockOrderProductController.
type MockOrderProductControllerMockRecorder struct {
	mock *MockOrderProductController
}

// NewMockOrderProductController creates a new mock instance.
func NewMockOrderProductController(ctrl *gomock.Controller) *MockOrderProductController {
	mock := &MockOrderProductController{ctrl: ctrl}
	mock.recorder = &MockOrderProductControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProductController) EXPECT() *MockOrderProductControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderProductController) Create(ctx context.Context, presenter port.Presenter, input dto.CreateOrderProductInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderProductControllerMockRecorder) Create(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderProductController)(nil).Create), ctx, presenter, input)
}

// Delete mocks base method.
func (m *MockOrderProductController) Delete(ctx context.Context, presenter port.Presenter, input dto.DeleteOrderProductInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderProductControllerMockRecorder) Delete(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderProductController)(nil).Delete), ctx, presenter, input)
}

// Get mocks base method.
func (m *MockOrderProductController) Get(ctx context.Context, presenter port.Presenter, input dto.GetOrderProductInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderProductControllerMockRecorder) Get(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderProductController)(nil).Get), ctx, presenter, input)
}

// List mocks base method.
func (m *MockOrderProductController) List(ctx context.Context, presenter port.Presenter, input dto.ListOrderProductsInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderProductControllerMockRecorder) List(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderProductController)(nil).List), ctx, presenter, input)
}

// Update mocks base method.
func (m *MockOrderProductController) Update(ctx context.Context, presenter port.Presenter, input dto.UpdateOrderProductInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrderProductControllerMockRecorder) Update(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrderProductController)(nil).Update), ctx, presenter, input)
}
