// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_history_gateway_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_history_gateway_port.go -destination=internal/core/port/mocks/order_history_gateway_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	valueobject "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/value_object"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderHistoryGateway is a mock of OrderHistoryGateway interface.
type MockOrderHistoryGateway struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHistoryGatewayMockRecorder
	isgomock struct{}
}

// MockOrderHistoryGatewayMockRecorder is the mock recorder for MockOrderHistoryGateway.
type MockOrderHistoryGatewayMockRecorder struct {
	mock *MockOrderHistoryGateway
}

// NewMockOrderHistoryGateway creates a new mock instance.
func NewMockOrderHistoryGateway(ctrl *gomock.Controller) *MockOrderHistoryGateway {
	mock := &MockOrderHistoryGateway{ctrl: ctrl}
	mock.recorder = &MockOrderHistoryGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHistoryGateway) EXPECT() *MockOrderHistoryGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderHistoryGateway) Create(ctx context.Context, entity *entity.OrderHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderHistoryGatewayMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderHistoryGateway)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockOrderHistoryGateway) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderHistoryGatewayMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderHistoryGateway)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockOrderHistoryGateway) FindAll(ctx context.Context, orderID uint64, status valueobject.OrderStatus, page, limit int) ([]*entity.OrderHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, orderID, status, page, limit)
	ret0, _ := ret[0].([]*entity.OrderHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrderHistoryGatewayMockRecorder) FindAll(ctx, orderID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrderHistoryGateway)(nil).FindAll), ctx, orderID, status, page, limit)
}

// FindByID mocks base method.
func (m *MockOrderHistoryGateway) FindByID(ctx context.Context, id uint64) (*entity.OrderHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.OrderHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderHistoryGatewayMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderHistoryGateway)(nil).FindByID), ctx, id)
}
