// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_history_controller_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_history_controller_port.go -destination=internal/core/port/mocks/order_history_controller_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	port "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/port"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderHistoryController is a mock of OrderHistoryController interface.
type MockOrderHistoryController struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHistoryControllerMockRecorder
	isgomock struct{}
}

// MockOrderHistoryControllerMockRecorder is the mock recorder for MockOrderHistoryController.
type MockOrderHistoryControllerMockRecorder struct {
	mock *MockOrderHistoryController
}

// NewMockOrderHistoryController creates a new mock instance.
func NewMockOrderHistoryController(ctrl *gomock.Controller) *MockOrderHistoryController {
	mock := &MockOrderHistoryController{ctrl: ctrl}
	mock.recorder = &MockOrderHistoryControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHistoryController) EXPECT() *MockOrderHistoryControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderHistoryController) Create(ctx context.Context, presenter port.Presenter, input dto.CreateOrderHistoryInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderHistoryControllerMockRecorder) Create(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderHistoryController)(nil).Create), ctx, presenter, input)
}

// Delete mocks base method.
func (m *MockOrderHistoryController) Delete(ctx context.Context, presenter port.Presenter, input dto.DeleteOrderHistoryInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderHistoryControllerMockRecorder) Delete(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderHistoryController)(nil).Delete), ctx, presenter, input)
}

// Get mocks base method.
func (m *MockOrderHistoryController) Get(ctx context.Context, presenter port.Presenter, input dto.GetOrderHistoryInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderHistoryControllerMockRecorder) Get(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderHistoryController)(nil).Get), ctx, presenter, input)
}

// List mocks base method.
func (m *MockOrderHistoryController) List(ctx context.Context, presenter port.Presenter, input dto.ListOrderHistoriesInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderHistoryControllerMockRecorder) List(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderHistoryController)(nil).List), ctx, presenter, input)
}
