// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/payment_controller_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/payment_controller_port.go -destination=internal/core/port/mocks/payment_controller_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	port "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/port"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentController is a mock of PaymentController interface.
type MockPaymentController struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentControllerMockRecorder
	isgomock struct{}
}

// MockPaymentControllerMockRecorder is the mock recorder for MockPaymentController.
type MockPaymentControllerMockRecorder struct {
	mock *MockPaymentController
}

// NewMockPaymentController creates a new mock instance.
func NewMockPaymentController(ctrl *gomock.Controller) *MockPaymentController {
	mock := &MockPaymentController{ctrl: ctrl}
	mock.recorder = &MockPaymentControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentController) EXPECT() *MockPaymentControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentController) Create(ctx context.Context, presenter port.Presenter, input dto.CreatePaymentInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentControllerMockRecorder) Create(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentController)(nil).Create), ctx, presenter, input)
}

// Get mocks base method.
func (m *MockPaymentController) Get(ctx context.Context, p port.Presenter, i dto.GetPaymentInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, p, i)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentControllerMockRecorder) Get(ctx, p, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentController)(nil).Get), ctx, p, i)
}

// Update mocks base method.
func (m *MockPaymentController) Update(ctx context.Context, p port.Presenter, i dto.UpdatePaymentInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p, i)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPaymentControllerMockRecorder) Update(ctx, p, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentController)(nil).Update), ctx, p, i)
}
