// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/product_datasource_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/product_datasource_port.go -destination=internal/core/port/mocks/product_datasource_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockProductDataSource is a mock of ProductDataSource interface.
type MockProductDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockProductDataSourceMockRecorder
	isgomock struct{}
}

// MockProductDataSourceMockRecorder is the mock recorder for MockProductDataSource.
type MockProductDataSourceMockRecorder struct {
	mock *MockProductDataSource
}

// NewMockProductDataSource creates a new mock instance.
func NewMockProductDataSource(ctrl *gomock.Controller) *MockProductDataSource {
	mock := &MockProductDataSource{ctrl: ctrl}
	mock.recorder = &MockProductDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductDataSource) EXPECT() *MockProductDataSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductDataSource) Create(ctx context.Context, product *entity.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductDataSourceMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductDataSource)(nil).Create), ctx, product)
}

// Delete mocks base method.
func (m *MockProductDataSource) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductDataSourceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductDataSource)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockProductDataSource) FindAll(ctx context.Context, filters map[string]any, page, limit int) ([]*entity.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters, page, limit)
	ret0, _ := ret[0].([]*entity.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockProductDataSourceMockRecorder) FindAll(ctx, filters, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockProductDataSource)(nil).FindAll), ctx, filters, page, limit)
}

// FindByID mocks base method.
func (m *MockProductDataSource) FindByID(ctx context.Context, id uint64) (*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductDataSourceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductDataSource)(nil).FindByID), ctx, id)
}

// Transaction mocks base method.
func (m *MockProductDataSource) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockProductDataSourceMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockProductDataSource)(nil).Transaction), ctx, fn)
}

// Update mocks base method.
func (m *MockProductDataSource) Update(ctx context.Context, product *entity.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductDataSourceMockRecorder) Update(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductDataSource)(nil).Update), ctx, product)
}
