// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/staff_datasource_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/staff_datasource_port.go -destination=internal/core/port/mocks/staff_datasource_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStaffDataSource is a mock of StaffDataSource interface.
type MockStaffDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockStaffDataSourceMockRecorder
	isgomock struct{}
}

// MockStaffDataSourceMockRecorder is the mock recorder for MockStaffDataSource.
type MockStaffDataSourceMockRecorder struct {
	mock *MockStaffDataSource
}

// NewMockStaffDataSource creates a new mock instance.
func NewMockStaffDataSource(ctrl *gomock.Controller) *MockStaffDataSource {
	mock := &MockStaffDataSource{ctrl: ctrl}
	mock.recorder = &MockStaffDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffDataSource) EXPECT() *MockStaffDataSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStaffDataSource) Create(ctx context.Context, staff *entity.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStaffDataSourceMockRecorder) Create(ctx, staff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStaffDataSource)(nil).Create), ctx, staff)
}

// Delete mocks base method.
func (m *MockStaffDataSource) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffDataSourceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffDataSource)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockStaffDataSource) FindAll(ctx context.Context, filters map[string]any, page, limit int) ([]*entity.Staff, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters, page, limit)
	ret0, _ := ret[0].([]*entity.Staff)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockStaffDataSourceMockRecorder) FindAll(ctx, filters, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockStaffDataSource)(nil).FindAll), ctx, filters, page, limit)
}

// FindByID mocks base method.
func (m *MockStaffDataSource) FindByID(ctx context.Context, id uint64) (*entity.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStaffDataSourceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStaffDataSource)(nil).FindByID), ctx, id)
}

// Transaction mocks base method.
func (m *MockStaffDataSource) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockStaffDataSourceMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockStaffDataSource)(nil).Transaction), ctx, fn)
}

// Update mocks base method.
func (m *MockStaffDataSource) Update(ctx context.Context, staff *entity.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStaffDataSourceMockRecorder) Update(ctx, staff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStaffDataSource)(nil).Update), ctx, staff)
}
