// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/staff_usecase_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/staff_usecase_port.go -destination=internal/core/port/mocks/staff_usecase_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/domain/entity"
	dto "github.com/FIAP-SOAT-G20/fiap-tech-challenge-3-api/internal/core/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockStaffUseCase is a mock of StaffUseCase interface.
type MockStaffUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStaffUseCaseMockRecorder
	isgomock struct{}
}

// MockStaffUseCaseMockRecorder is the mock recorder for MockStaffUseCase.
type MockStaffUseCaseMockRecorder struct {
	mock *MockStaffUseCase
}

// NewMockStaffUseCase creates a new mock instance.
func NewMockStaffUseCase(ctrl *gomock.Controller) *MockStaffUseCase {
	mock := &MockStaffUseCase{ctrl: ctrl}
	mock.recorder = &MockStaffUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffUseCase) EXPECT() *MockStaffUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStaffUseCase) Create(ctx context.Context, input dto.CreateStaffInput) (*entity.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*entity.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStaffUseCaseMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStaffUseCase)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockStaffUseCase) Delete(ctx context.Context, input dto.DeleteStaffInput) (*entity.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*entity.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffUseCaseMockRecorder) Delete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffUseCase)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockStaffUseCase) Get(ctx context.Context, input dto.GetStaffInput) (*entity.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*entity.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStaffUseCaseMockRecorder) Get(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStaffUseCase)(nil).Get), ctx, input)
}

// List mocks base method.
func (m *MockStaffUseCase) List(ctx context.Context, input dto.ListStaffsInput) ([]*entity.Staff, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]*entity.Staff)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStaffUseCaseMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStaffUseCase)(nil).List), ctx, input)
}

// Update mocks base method.
func (m *MockStaffUseCase) Update(ctx context.Context, input dto.UpdateStaffInput) (*entity.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*entity.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStaffUseCaseMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStaffUseCase)(nil).Update), ctx, input)
}
