name: ci/unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🚀 Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: 🛠️ Create .env
      run: cp .env.example .env

    - name: ✅ Run tests
      run: make test
