name: ci/go-test-coverage

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: check test coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        continue-on-error: true # Should fail after coverage comment is posted
        with:
          config: ./.github/.testcoverage.yml

      # Post coverage report as comment (in 2 steps)
      - name: find pull request ID
        run: |
          if [ -z "${{ github.event.pull_request }}" ]; then
            echo "pull_request_id=0" >> $GITHUB_ENV
          else
            echo "pull_request_id=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi
      - name: post coverage report
        if: env.pull_request_id
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: coverage-report
          pr-number: ${{ env.pull_request_id }}
          message: |
            go-test-coverage report:
            ```
            ${{ steps.coverage.outputs.report }}
            ```

      - name: "finally check coverage"
        if: steps.coverage.outcome == 'failure'
        shell: bash
        run: echo "coverage check failed" && exit 1
