name: ci/security-checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golang/govulncheck-action@v1
